# Generated by Django 5.2.14 on 2026-05-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_national_id_photo'),
        ('sales', '0002_saleitem'),
        ('services', '0003_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='services.service'),
        ),
    ]
