# Generated by Django 5.2.14 on 2026-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_per_employee_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override commission % for this item. Leave blank to use employee's default rate.", max_digits=5, null=True),
        ),
    ]
