# Generated by Django 5.2.14 on 2026-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_payment_and_support_commission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_status_89a0f1_idx',
            old_name='sales_sale_status__3e0b1d_idx',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override main employee commission %. Leave blank to use employee/default service rate.', max_digits=5, null=True),
        ),
    ]
