# Generated by Django 5.2.14 on 2026-05-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_phone_8493fa_idx',
            old_name='customers_c_phone_d9a31a_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_name_f018e2_idx',
            old_name='customers_c_name_f3379c_idx',
        ),
    ]
