# Generated by Django 5.2.14 on 2026-06-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_c_phone_d9a31a_idx_customers_c_phone_8493fa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_phone_8493fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_name_f018e2_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferences',
        ),
    ]
