# Generated by Django 5.2.14 on 2026-05-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityalert',
            options={'ordering': ['resolved', '-created_at', '-id']},
        ),
    ]
