# Generated by Django 5.2.14 on 2026-05-07 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='pcs', help_text='e.g. pcs, ml, kg, bottle', max_length=40)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when stock falls at or below this level.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('adjustment', 'Adjustment')], default='restock', max_length=20)),
                ('quantity', models.IntegerField(help_text='Use negative values for usage/removal.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
