# Generated by Django 5.2.14 on 2026-05-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_stock_and_product_sales'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_categor_062220_idx',
            old_name='inventory_p_categor_1baf0a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_is_acti_47a270_idx',
            old_name='inventory_p_is_acti_68ad4c_idx',
        ),
        migrations.RenameIndex(
            model_name='productsale',
            new_name='inventory_p_sale_da_55dc4f_idx',
            old_name='inventory_p_sale_da_0e2b99_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentry',
            new_name='inventory_s_date_dcf1f1_idx',
            old_name='inventory_s_date_3e5438_idx',
        ),
    ]
