# Generated by Django 5.2.14 on 2026-05-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productsale_payment_method'),
        ('sales', '0008_ensure_payment_method_database_column'),
        ('services', '0005_haircut_scrubbing_support_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='related_sale_item',
            field=models.ForeignKey(blank=True, help_text='Service sale item that consumed this stock, when auto-deducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_usage_entries', to='sales.saleitem'),
        ),
        migrations.CreateModel(
            name='ServiceStockUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Units consumed each time this service is approved.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_usages', to='services.service')),
            ],
            options={
                'ordering': ['service__name', 'product__name'],
                'unique_together': {('service', 'product')},
            },
        ),
    ]
