# Generated by Django 5.2.14 on 2026-06-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockentry_related_sale_item_servicestockusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='related_sale_item',
        ),
        migrations.DeleteModel(
            name='ServiceStockUsage',
        ),
    ]
