# Generated by Django 5.2.14 on 2026-05-14 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, unique=True)),
                ('service_sales_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('product_sales_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('mobile_money_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('expenses_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_expenses_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('mobile_money_reference', models.CharField(blank=True, max_length=140)),
                ('pending_approvals_confirmed', models.BooleanField(default=False)),
                ('expenses_confirmed', models.BooleanField(default=False)),
                ('commissions_confirmed', models.BooleanField(default=False)),
                ('mobile_money_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closeouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date'],
                'indexes': [models.Index(fields=['business_date', 'closed_at'], name='reports_dai_busines_b27db5_idx')],
            },
        ),
    ]
