# Generated by Django 5.2.14 on 2026-05-09 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_identification_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, help_text='Upload JPG, JPEG, PNG, or WEBP. Avoid HEIF/Live Photos on shared hosting.', upload_to='employees/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
