# Generated by Django 5.2.14 on 2026-05-09 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, help_text='Upload JPG, JPEG, PNG, or WEBP. /Live Photos on shared hosting.', upload_to='employees/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'HEIF'])]),
        ),
    ]
