# Generated by Django 5.2.14 on 2026-05-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expand_expense_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_expense_23d62f_idx',
            old_name='expenses_ex_expense_9770d5_idx',
        ),
    ]
